baseURL: "https://www.istoa.eu"
title: iStoa
pagination:pagerSize: 5
theme: PaperMod

DefaultContentLanguage: en

languages:
  en:
    contentDir: content/en
    languageName: English
    languageCode: en
    weight: 10
  fr:
    contentDir: content/fr
    languageName: Français
    languageCode: fr
    weight: 20
    params:
      profileMode:
        enabled: true
        title: Modèle Dynamique de Connaissance
        subtitle: simulations pour apprendre
        buttons:
          - name: dkm
            url:  dkm
          - name: télécharger
            url:  download
  es:
    contentDir: content/es
    languageName: Español
    languageCode: es
    weight: 30
    params:
      profileMode:
        enabled: true
        title: Modelos Dinámicos de Conocimiento
        subtitle: simulaciones para aprender
        buttons:
          - name: dkm
            url: dkm
          - name: descargar
            url: download
  de:
    contentDir: content/de
    languageName: Deutsch
    languageCode: de
    weight: 40
    params:
      profileMode:
        enabled: true
        title: Dynamische Wissensmodelle
        subtitle: Simulationen zum Lernen
        buttons:
          - name: dkm
            url: dkm
          - name: herunterladen
            url: download
  zh:
    contentDir: content/zh
    languageName: 简体中文
    languageCode: zh
    weight: 50
    params:
      profileMode:
        enabled: true
        title: 动态知识模型
        subtitle: 用于学习的模拟
        buttons:
          - name: dkm
            url: dkm
          - name: 下载
            url: download
  zh-tw:
    contentDir: content/zh-TW
    languageName: 繁體中文
    languageCode: zh-tw
    weight: 60
    params:
      profileMode:
        enabled: true
        title: 動態知識模型
        subtitle: 用於學習的模擬
        buttons:
          - name: dkm
            url: dkm
          - name: 下載
            url: download

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  displayFullLangName: true
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: iStoa
  author: hlsf
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: true
  ShareButtons: ["reddit"]
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  # profile-mode
  profileMode:
    enabled: true
    title: Dynamic Knowledge Model
    subtitle: simulations for learning
    imageUrl: "istoa.png"
    imageWidth: 250
    imageHeight: 150
    buttons:
      - name: dkm
        url:  dkm
      - name: download
        url:  download

  socialIcons:
    - name: mastodon
      url:  "https://mamot.fr/@drgeo"
    - name: github
      url: "https://github.com/istoa-eu/app/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
markup:
  highlight:
    noClasses: false
    tabWidth: 3
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    lineNos: false
    style: rrt