main:
  - name: dkm
    url: dkm
    weight: 10
  - name: herunterladen
    url: download
    weight: 20
  - name: unterstützen sie uns
    url: support-us
    weight: 30
  - name: unsere aktivitäten
    url: our-actions
    weight: 40
  - name: über uns
    url: about
    weight: 50