main:
  - name: dkm
    url: /dkm
    weight: 10
  - name: download
    url: /download
    weight: 20
  - name: support us
    url: /support-us
    weight: 30
  - name: our actions
    url: /our-actions
    weight: 40
  - name: about
    url: /about
    weight: 50      
